version: "3.11"

services:
  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
    volumes:
      - ./app:/code/app
      - ./weather.db:/code/weather.db
